version: "3.8"
services:
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: arduino_data
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  servidor:
    build:
      context: ./servidor
    container_name: servidor
    depends_on:
      - database
    ports:
      - "8080:8080"
    volumes:
      - ./servidor:/app
